{{- if not .Values.hologram.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hologram-mqtt.fullname" . }}-hologram
  labels:
    {{- include "hologram-mqtt.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.hologram.apiKey | quote }}
{{- end }}
---
{{- if and (not .Values.mqtt.existingSecret) (or .Values.mqtt.username .Values.mqtt.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hologram-mqtt.fullname" . }}-mqtt
  labels:
    {{- include "hologram-mqtt.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.mqtt.username | quote }}
  password: {{ .Values.mqtt.password | quote }}
{{- end }}
