apiVersion: v1
kind: Service
metadata:
  name: {{ include "hologram-mqtt.fullname" . }}
  labels:
    {{- include "hologram-mqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "hologram-mqtt.selectorLabels" . | nindent 4 }}
